# Generated by Django 4.2.6 on 2023-10-12 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='use',
            new_name='link_image',
        ),
    ]
